image:
  file: .gitpod.Dockerfile
tasks:
  - name: Start Docker Daemon
    command: sudo docker-up &
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
    name: Use AWS CLI
    command: brew install awscli
ports:
  - port: 5000
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false
